-- Drop tables in reverse dependency order
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS execution CASCADE;
DROP TABLE IF EXISTS academic_performance CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS schedule CASCADE;
DROP TABLE IF EXISTS discipline CASCADE;
DROP TABLE IF EXISTS week CASCADE;
DROP TABLE IF EXISTS subject CASCADE;
DROP TABLE IF EXISTS student_profile CASCADE;
DROP TABLE IF EXISTS staff_profile CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS auditorium CASCADE;
DROP TABLE IF EXISTS "group" CASCADE;
DROP TABLE IF EXISTS vocation CASCADE;
DROP TABLE IF EXISTS faculty CASCADE;

-- Drop enum types
DROP TYPE IF EXISTS lesson_type;
DROP TYPE IF EXISTS auditorium_type;

-- Drop extension
DROP EXTENSION IF EXISTS "uuid-ossp";