// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRecord(arg1, arg2) {
  return window['go']['main']['App']['CreateRecord'](arg1, arg2);
}

export function CurrentUser() {
  return window['go']['main']['App']['CurrentUser']();
}

export function DashboardStats() {
  return window['go']['main']['App']['DashboardStats']();
}

export function DeleteRecord(arg1, arg2) {
  return window['go']['main']['App']['DeleteRecord'](arg1, arg2);
}

export function GetRecord(arg1, arg2) {
  return window['go']['main']['App']['GetRecord'](arg1, arg2);
}

export function ListOptions(arg1) {
  return window['go']['main']['App']['ListOptions'](arg1);
}

export function ListRecords(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListRecords'](arg1, arg2, arg3, arg4);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function RestoreSession(arg1) {
  return window['go']['main']['App']['RestoreSession'](arg1);
}

export function ScheduleFilters() {
  return window['go']['main']['App']['ScheduleFilters']();
}

export function UpdateRecord(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateRecord'](arg1, arg2, arg3);
}

export function WeeklySchedule(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WeeklySchedule'](arg1, arg2, arg3, arg4);
}
