// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';

export function CreateRecord(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function CurrentUser():Promise<services.CurrentUserView>;

export function DashboardStats():Promise<models.DashboardStats>;

export function DeleteRecord(arg1:string,arg2:string):Promise<void>;

export function GetRecord(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ListOptions(arg1:string):Promise<Array<models.OptionItem>>;

export function ListRecords(arg1:string,arg2:string,arg3:number,arg4:number):Promise<models.PageResult>;

export function Login(arg1:services.LoginRequest):Promise<services.AuthResponse>;

export function Logout():Promise<void>;

export function Ping():Promise<string>;

export function RestoreSession(arg1:string):Promise<services.CurrentUserView>;

export function ScheduleFilters():Promise<services.ScheduleFilters>;

export function UpdateRecord(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Record<string, any>>;

export function WeeklySchedule(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<Record<string, any>>>;
